/***
	@TABLE_PREFIXES
	SET COMMA DELIMITED TABLE NAMES OR PREFIX OF TABLE NAME
	i.e,
		'POP,SOP'
		'POP10110,SOP10100,RM10100'
		'SOP10100'
	
	@FIND_VALUES
	SET TO 0 (FALSE) IF YOU ONLY WANT TO SHOW RELATIONSHIPS
***/
DECLARE 
	@TABLE_PREFIXES AS NVARCHAR(128) = 'POP',
	@FIND_VALUES AS BIT = 1

IF OBJECT_ID(N'tempdb..##RELATIONSHIPS') IS NOT NULL
BEGIN
	DROP TABLE ##RELATIONSHIPS
END


IF OBJECT_ID(N'tempdb..##FOR_ANALYSIS') IS NOT NULL
BEGIN
	DROP TABLE ##FOR_ANALYSIS
END

IF OBJECT_ID(N'tempdb..##FOUND_RELATIONSHIP') IS NOT NULL
BEGIN
	DROP TABLE ##FOUND_RELATIONSHIP
END

IF OBJECT_ID(N'tempdb..##LASTCHECK') IS NOT NULL
BEGIN
	DROP TABLE ##LASTCHECK
END


SET NOCOUNT ON;

;WITH module_tables as 
(
	SELECT b.TABLE_NAME as MODULE_TABLE_NAME, b.COLUMN_NAME, b.ORDINAL_POSITION, b.IS_NULLABLE, b.DATA_TYPE, b.CHARACTER_MAXIMUM_LENGTH, b.NUMERIC_PRECISION, b.NUMERIC_SCALE  FROM CompanyMerge..fn_ALB_CM_Split_v2(@TABLE_PREFIXES,',') a
	INNER JOIN INFORMATION_SCHEMA.COLUMNS b ON b.TABLE_NAME LIKE a.[Data] + '%'
)
,
module_tables_primary_key as
(
	SELECT DISTINCT module_tables.MODULE_TABLE_NAME, 'PRIMARY' as REFERENCE, ss.PrimaryTableName as REFERENCE_TABLE_NAME, module_tables.COLUMN_NAME
	  FROM [dbo].[CompanyMerge_Vw_PrimaryForeignRelationshipSummary] [ss]
	  INNER JOIN module_tables on  [ss].PrimaryFieldName = module_tables.COLUMN_NAME	  
)
,
module_tables_foreign_key as 
(
	SELECT DISTINCT module_tables.MODULE_TABLE_NAME, 'FOREIGN' as REFERENCE, ss.ForeignTableName as REFERENCE_TABLE_NAME, module_tables.COLUMN_NAME
	  FROM [dbo].[CompanyMerge_Vw_PrimaryForeignRelationshipSummary] [ss]
	  INNER JOIN module_tables ON ss.ForeignFieldName = module_tables.COLUMN_NAME
	  WHERE NOT EXISTS 
		(
			SELECT NULL 
			FROM module_tables_primary_key 
			WHERE
				ss.ForeignFieldName = module_tables_primary_key.COLUMN_NAME AND
				ss.ForeignTableName = module_tables_primary_key.REFERENCE_TABLE_NAME
		)
 ),
 z as 
 (
	 SELECT *, NULL as PRIMARY_TABLE, NULL as PRIMARY_COLUMN FROM module_tables_primary_key
	 UNION ALL
	 SELECT a.*, ss.PrimaryTableName as PRIMARY_TABLE, ss.PrimaryFieldName as PRIMARY_COLUMN  FROM module_tables_foreign_key a
		inner join [dbo].[CompanyMerge_Vw_PrimaryForeignRelationshipSummary] [ss] ON 
		a.REFERENCE_TABLE_NAME = ss.ForeignTableName AND a.COLUMN_NAME = ss.ForeignFieldName
 )
SELECT DISTINCT MODULE_TABLE_NAME, 
	PRIMARY_TABLE, 
	PRIMARY_COLUMN, 
	REFERENCE, 
	REFERENCE_TABLE_NAME, 
	COLUMN_NAME 
INTO ##RELATIONSHIPS
FROM z 
 
 IF @FIND_VALUES = 0
 BEGIN
 	 SELECT DISTINCT MODULE_TABLE_NAME, 
		PRIMARY_TABLE, 
		PRIMARY_COLUMN, 
		REFERENCE, 
		REFERENCE_TABLE_NAME, 
		COLUMN_NAME 
		FROM ##RELATIONSHIPS 			
		ORDER BY MODULE_TABLE_NAME, REFERENCE, REFERENCE_TABLE_NAME, COLUMN_NAME
	RETURN
 END
	;WITH tt as
	(
 		SELECT DISTINCT
		MODULE_TABLE_NAME, 
		PRIMARY_TABLE, 
		PRIMARY_COLUMN, 
		REFERENCE, 
		REFERENCE_TABLE_NAME, 
		COLUMN_NAME	
		FROM ##RELATIONSHIPS 
	),rr as
	(
	select *, ROW_NUMBER() OVER(ORDER BY MODULE_TABLE_NAME, REFERENCE, REFERENCE_TABLE_NAME, COLUMN_NAME) AS __row
		FROM tt
		WHERE EXISTS (select * FROM INFORMATION_SCHEMA.TABLES b WHERE tt.REFERENCE_TABLE_NAME = b.TABLE_NAME)
		AND PRIMARY_TABLE != REFERENCE_TABLE_NAME
	)
	select * into  ##FOR_ANALYSIS FROM rr
	
	DECLARE @currRow AS INT = 1
	DECLARE @lastRow AS INT = (SELECT TOP 1 __row FROM ##FOR_ANALYSIS ORDER BY __row DESC)
		
	SELECT CONVERT(NVARCHAR(512),'') AS 'MAIN', CONVERT(NVARCHAR(512),'') AS 'COLUMN', CONVERT(NVARCHAR(512),'') AS 'PRIMARY_TABLE', CONVERT(NVARCHAR(512),'') AS 'PRIMARY_COLUMN', 0 AS ROW_COUNT 
	INTO ##FOUND_RELATIONSHIP
	DELETE FROM ##FOUND_RELATIONSHIP WHERE MAIN = ''

	WHILE @lastRow >= @currRow
	BEGIN		
		IF OBJECT_ID(N'tempdb..##TABLE_ANALYSIS') IS NOT NULL
		BEGIN
			DROP TABLE ##TABLE_ANALYSIS
		END

		DECLARE @query as NVARCHAR(1000) = '';
		DECLARE @row_count as int = 0;

		DECLARE 
			@MAIN_TABLE AS NVARCHAR(32) = '',
			@FOREIGN_TABLE AS NVARCHAR(32) = '',
			@PRIMARY_TABLE AS NVARCHAR(32) = '';

		DECLARE 
			@FOREIGN_KEY AS NVARCHAR(32) = '',
			@PRIMARY_KEY AS NVARCHAR(32) = ''

		SELECT TOP 1 @MAIN_TABLE = MODULE_TABLE_NAME, 
			@FOREIGN_TABLE = REFERENCE_TABLE_NAME,
			@PRIMARY_TABLE = PRIMARY_TABLE,
						
			@FOREIGN_KEY = COLUMN_NAME,
			@PRIMARY_KEY = PRIMARY_COLUMN			
		FROM ##FOR_ANALYSIS WHERE __row = @currRow		

		SET @query = 
		'SELECT DISTINCT [' + @MAIN_TABLE + '].[' + @FOREIGN_KEY + ']' + CHAR(13)
		 + 'INTO ##TABLE_ANALYSIS ' + CHAR(13)
		 + 'FROM [' + DB_NAME() + ']..[' + @MAIN_TABLE+ '] ' + CHAR(13) +
			 CASE
				WHEN @MAIN_TABLE != @FOREIGN_TABLE THEN
					'INNER JOIN [' + DB_NAME() + ']..[' + @FOREIGN_TABLE + '] ON [' + @MAIN_TABLE+ '].[' + @FOREIGN_KEY + '] = [' + @FOREIGN_TABLE + '].[' + @FOREIGN_KEY + '] ' + CHAR(13)
				ELSE ''
				END
		 +
		 CASE
				WHEN @MAIN_TABLE != @PRIMARY_TABLE THEN
					'INNER JOIN [' + DB_NAME() + ']..[' + @PRIMARY_TABLE + '] ON [' + @FOREIGN_TABLE + '].[' + @FOREIGN_KEY + '] = [' + @PRIMARY_TABLE+ '].[' + @PRIMARY_KEY + '] ' + CHAR(13)
				ELSE ''
				END


		PRINT(CHAR(13) +'TABLE: ' + @MAIN_TABLE + ' -> ' + @FOREIGN_TABLE + '.' + @FOREIGN_KEY + ' -> ' + @PRIMARY_TABLE +'.' + @PRIMARY_KEY )
		PRINT(REPLACE(@query, 'INTO ##TABLE_ANALYSIS ' + CHAR(13), ''))
		
		EXEC(@query)

		SELECT TOP 1 @row_count = COUNT(*) FROM ##TABLE_ANALYSIS

		PRINT('ROWS: ' + CONVERT(NVARCHAR(10),@row_count))

		INSERT INTO ##FOUND_RELATIONSHIP 
			(MAIN, [COLUMN], [PRIMARY_TABLE], [PRIMARY_COLUMN], ROW_COUNT)
		VALUES
			(@MAIN_TABLE,  @FOREIGN_KEY, @PRIMARY_TABLE, @PRIMARY_KEY, @row_count)
		
		SET @currRow += 1
	END

  --ANOTHER LAYER OF CHECKING
	;with ll as
	(
		SELECT DISTINCT [MAIN], [COLUMN], [PRIMARY_TABLE], [PRIMARY_COLUMN]  FROM ##FOUND_RELATIONSHIP
		WHERE ROW_COUNT = 0
	)
	,
	mm as
	(
		SELECT *,  ROW_NUMBER() OVER (ORDER BY [MAIN], [COLUMN], [PRIMARY_TABLE], [PRIMARY_COLUMN]) AS __seq from ll
	)
	SELECT * INTO ##LASTCHECK FROM mm

	SET @currRow = 1
	SET @lastRow = (SELECT TOP 1 __seq FROM ##LASTCHECK ORDER BY __seq DESC)

	WHILE @lastRow >= @currRow
	BEGIN
		IF OBJECT_ID(N'tempdb..##TABLE_ANALYSIS_2') IS NOT NULL
		BEGIN
			DROP TABLE ##TABLE_ANALYSIS_2
		END
		DECLARE @COLUMN AS NVARCHAR(32) = '';

		SELECT TOP 1 @MAIN_TABLE = MAIN,
			@COLUMN =  [COLUMN],
			@PRIMARY_TABLE =  [PRIMARY_TABLE],
			@PRIMARY_KEY = PRIMARY_COLUMN
		FROM ##LASTCHECK WHERE __seq = @currRow

		IF @MAIN_TABLE = @PRIMARY_TABLE
		BEGIN
			SET @currRow += 1
			CONTINUE;
		END
		SET @query =
		'SELECT DISTINCT [' + @MAIN_TABLE + '].[' + @COLUMN + ']' + CHAR(13)
		 + 'INTO ##TABLE_ANALYSIS_2 ' + CHAR(13)
		 + 'FROM [' + DB_NAME() + ']..[' + @MAIN_TABLE+ '] ' + CHAR(13) +
		 + 'INNER JOIN [' + DB_NAME() + ']..[' + @PRIMARY_TABLE + '] ON [' + @MAIN_TABLE + '].[' + @COLUMN + '] = [' + @PRIMARY_TABLE+ '].[' + @PRIMARY_KEY + '] '

		EXEC(@query)

		SELECT TOP 1 @row_count = COUNT(*) FROM ##TABLE_ANALYSIS_2

		IF @row_count > 0
		BEGIN
			UPDATE ##FOUND_RELATIONSHIP
			SET
			ROW_COUNT = @row_count
			WHERE MAIN = @MAIN_TABLE
			AND [COLUMN] = @COLUMN
			AND [PRIMARY_COLUMN] = @PRIMARY_KEY
			AND [PRIMARY_TABLE] = @PRIMARY_TABLE
		END
		SET @currRow += 1
	END

	SELECT DISTINCT * FROM ##FOUND_RELATIONSHIP WHERE ROW_COUNT > 0
